### ISSUE TITLE
Program crashes when compiled with stateafl and ASAN

### ISSUE THREAD

**Issue by AAArdu** [stateafl/stateafl#2]
Thank you, I use stateafl and AddressSanitier to compile the program. The program crashes which seems there is something wrong with the instrumentation of stateafl. The crash information:

==3564==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fbaef977020 at pc 0x000000435ccc bp 0x7fff557baf40 sp 0x7fff557ba700
WRITE of size 776 at 0x7fbaef977020 thread T0
    #0 0x435ccb in memset /home/brian/src/final/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:783:3
    #1 0x5b4f6c in memset /usr/include/x86_64-linux-gnu/bits/string_fortified.h:71:10
    #2 0x5b4f6c in new_alloc_record /stateafl/llvm_mode/afl-llvm-rt-state-tracer.o.c:579:3
    #3 0x5b4f6c in new_stack_alloc_record /stateafl/llvm_mode/afl-llvm-rt-state-tracer.o.c:662:3
    #4 0x4c802a in main/protocols/mqtt/mosquitto/mosquitto_stateafl/src/mosquitto.c:441:2
    #5 0x7fbaf2beabf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #6 0x41f569 in _start (/mosquitto_stateafl/src/mosquitto+0x41f569)

Address 0x7fbaef977020 is located in stack of thread T0 at offset 32 in frame
    #0 0x4c7f2f in main /mosquitto_stateafl/src/mosquitto.c:440

  This frame has 2 object(s):
    [32, 808) 'config' (line 441) <== Memory access at offset 32 is inside this variable
    [944, 960) 'tv' (line 449)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope /home/brian/src/final/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:783:3 in memset
Shadow bytes around the buggy address:
  0x0ff7ddf26db0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff7ddf26dc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff7ddf26dd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff7ddf26de0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff7ddf26df0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff7ddf26e00: f1 f1 f1 f1[f8]f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0ff7ddf26e10: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0ff7ddf26e20: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0ff7ddf26e30: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0ff7ddf26e40: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0ff7ddf26e50: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3564==ABORTING

**Comment by rnatella** [comment]
@AAArdu I just commited an update to support ASAN with StateAFL. Profuzzbench has also been updated to use ASAN. Can you kindly test it on your application?

Note that, if ASAN is enabled, we rely on it to zero-initialize stack data. You will need to configure the following options:
```
export ASAN_OPTIONS='abort_on_error=1:symbolize=0:detect_leaks=0:detect_stack_use_after_return=1:detect_container_overflow=0:poison_array_cookie=0'
```
